global:
  lifeCycle:
    onStartWatch:
      - "bash cmd.sh up"
    onAfterChange:
      - dir: ""
        cmd: "bash cmd.sh rmi"
    onFinishWatch:
      - "bash cmd.sh down"
watchTargets:
  # spring
  - path: "backend/backoffice/src/main"
    lifeCycle:
      onChange:
        - dir: "backend/backoffice"
          cmd: "bash cmd.sh build update"
    option:
      excludeDir:
        - "backend/backoffice/src/main/generated"
      waitMillisecond: 1000
  # react
  - path: 'frontend/backoffice'
    lifeCycle:
      onStartWatch:
        - 'bash cmd.sh watch'
    option:
      excludeDir:
        - "frontend/backoffice"
      waitMillisecond: 1000 # default 100
  - path: 'frontend/backoffice/dist'
    lifeCycle:
      onChange:
        - dir: "frontend/backoffice"
          cmd: "bash cmd.sh update"
    option:
      waitMillisecond: 1000 # default 100
