version: '3'
services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../caddy/site:/srv
      - ../caddy/data:/data
      - ../caddy/config:/config
    command: caddy run -watch -config /etc/caddy/Caddyfile
    restart: on-failure
  backend_backoffice:
    build:
      context: ../backend/backoffice
      dockerfile: run-bootJar.Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    working_dir: "/app"
    entrypoint:
      - "./wait-for-it.sh"
      - "mariadb:3306"
      - "-t"
      - "0"
      - "--"
      - "java"
      - "-jar"
      - "-Dspring.profiles.active=default"
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      - "app.jar"
  redis:
    build:
      context: ../backend/infra/redis
      dockerfile: Dockerfile
    volumes:
      - ../backend/infra/redis/data:/data
    ports:
      - "6379:6379"
    restart: always
  mariadb:
    image: mariadb:10.6
    volumes:
      - ../backend/infra/mariadb/conf.d:/etc/mysql/conf.d
      - ../backend/infra/mariadb/data:/var/lib/mysql
      - ../backend/infra/mariadb/initdb.d:/docker-entrypoint-initdb.d
    env_file: ../backend/infra/mariadb/.env
    environment:
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    restart: always
  frontend_backoffice:
    build:
      context: ../frontend/backoffice
      dockerfile: deploy-dist.Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
