.PHONY:go-update
go-update:
	(cd context/member/vo && go get -u ./...)
	(cd context/member/domain && go get -u ./...)
	(cd context/member/application && go get -u ./...)
	(cd context/member/adaptor && go get -u ./...)
	(cd runner/member-manager && go get -u ./...)
